//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMuaBanTuiXach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienTheSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienTheSanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.GioHang = new HashSet<GioHang>();
        }
    
        public int MaBienThe { get; set; }
        public int MaSanPham { get; set; }
        public string SKU { get; set; }
        public string MauSac { get; set; }
        public Nullable<decimal> ChieuDaiCM { get; set; }
        public Nullable<decimal> ChieuRongCM { get; set; }
        public Nullable<decimal> ChieuCaoCM { get; set; }
        public Nullable<int> CanNangGram { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<decimal> GiaGoc { get; set; }
        public int SoLuongTonKho { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHang { get; set; }
    }
}
