//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMuaBanTuiXach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public ChiTietDonHang()
        {
            this.PhieuDoiTra = new HashSet<PhieuDoiTra>();
        }
    
        public int MaChiTietDonHang { get; set; }
        public int MaDonHang { get; set; }
        public int MaBienThe { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaLucMua { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual ICollection<PhieuDoiTra> PhieuDoiTra { get; set; }
    }
}
