//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMuaBanTuiXach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public DanhMuc()
        {
            this.DanhMuc1 = new HashSet<DanhMuc>();
            this.SanPham = new HashSet<SanPham>();
        }
    
        public int MaDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MaDanhMucCha { get; set; }
        public string AnhDaiDien { get; set; }
    
        public virtual ICollection<DanhMuc> DanhMuc1 { get; set; }
        public virtual DanhMuc DanhMuc2 { get; set; }
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
