//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMuaBanTuiXach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChi
    {
        public DiaChi()
        {
            this.DonHang = new HashSet<DonHang>();
        }
    
        public int MaDiaChi { get; set; }
        public int MaNguoiDung { get; set; }
        public string TenNguoiNhan { get; set; }
        public string SoDienThoai { get; set; }
        public string SoNhaDuong { get; set; }
        public string PhuongXa { get; set; }
        public string QuanHuyen { get; set; }
        public string TinhThanhPho { get; set; }
        public Nullable<bool> LaMacDinh { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ICollection<DonHang> DonHang { get; set; }
    }
}
