//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMuaBanTuiXach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int MaMucGioHang { get; set; }
        public int MaNguoiDung { get; set; }
        public int MaBienThe { get; set; }
        public int SoLuong { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
