//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMuaBanTuiXach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDoiTra
    {
        public int MaPhieuDoiTra { get; set; }
        public int MaChiTietDonHang { get; set; }
        public int MaNguoiDung { get; set; }
        public string LoaiYeuCau { get; set; }
        public string LyDo { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
        public string GhiChuAdmin { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
