//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMuaBanTuiXach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_TuiXachEntities : DbContext
    {
        public QL_TuiXachEntities()
            : base("name=QL_TuiXachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BienTheSanPham> BienTheSanPham { get; set; }
        public DbSet<ChiTietDonHang> ChiTietDonHang { get; set; }
        public DbSet<DanhGia> DanhGia { get; set; }
        public DbSet<DanhMuc> DanhMuc { get; set; }
        public DbSet<DiaChi> DiaChi { get; set; }
        public DbSet<DonHang> DonHang { get; set; }
        public DbSet<GioHang> GioHang { get; set; }
        public DbSet<MaKhuyenMai> MaKhuyenMai { get; set; }
        public DbSet<NguoiDung> NguoiDung { get; set; }
        public DbSet<PhieuDoiTra> PhieuDoiTra { get; set; }
        public DbSet<SanPham> SanPham { get; set; }
        public DbSet<ThuongHieu> ThuongHieu { get; set; }
    }
}
