//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMuaBanTuiXach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.BienTheSanPham = new HashSet<BienTheSanPham>();
            this.DanhGia = new HashSet<DanhGia>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<int> MaThuongHieu { get; set; }
        public string ChatLieuChinh { get; set; }
        public string DipSuDung { get; set; }
        public string BoSuuTap { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual ICollection<BienTheSanPham> BienTheSanPham { get; set; }
        public virtual ICollection<DanhGia> DanhGia { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
