//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLMuaBanTuiXach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCa
    {
        public int MaPhanCa { get; set; }
        public int MaNguoiDung { get; set; }
        public int MaCa { get; set; }
        public System.DateTime NgayLamViec { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CaLamViec CaLamViec { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
